"""
Test Script Export Functionality

Tests the storyboard/script export mechanism including:
- ScriptGenerator querying database
- FountainFormatter generating Fountain markup
- StoryboardJSONFormatter generating structured JSON
- ExportPipeline integration
"""

import pytest
from pathlib import Path
from storage import GraphStore
from reporting.script_generator import ScriptGenerator
from reporting.export_pipeline import ExportPipeline
from reporting.query_engine import EnhancedQueryEngine


def test_script_generator_basic():
    """Test ScriptGenerator with empty database"""
    # Create in-memory database
    store = GraphStore("sqlite:///:memory:")

    # Create generator
    generator = ScriptGenerator(store)

    # Generate script (should handle empty gracefully)
    script_data = generator.generate_script_structure(
        world_id="test_world",
        title="Test Script"
    )

    # Verify structure
    assert script_data.title == "Test Script"
    assert script_data.world_id == "test_world"
    assert script_data.temporal_mode == "pearl"
    assert len(script_data.scenes) == 0  # No data in database
    assert len(script_data.characters) == 0


def test_fountain_export_empty():
    """Test Fountain export with empty database"""
    # Create in-memory database
    store = GraphStore("sqlite:///:memory:")

    # Create export pipeline
    engine = EnhancedQueryEngine()
    engine.store = store  # Attach store for script generation
    exporter = ExportPipeline(engine)

    # Export as Fountain
    output_path = "test_empty_script.fountain"

    try:
        result = exporter.export_report(
            world_id="test_world",
            report_type="script",
            export_format="fountain",
            output_path=output_path,
            title="Empty Test Script"
        )

        # Verify metadata
        assert result["report_type"] == "script"
        assert result["export_format"] == "fountain"
        assert "output_path" in result

        # Verify file was created
        assert Path(result["output_path"]).exists()

        # Read and verify content
        content = Path(result["output_path"]).read_text()
        assert "Title: Empty Test Script" in content
        assert "Generated by Timepoint-Daedalus" in content

        print("✅ Fountain export test passed")
        print(f"   Output: {result['output_path']}")
        print(f"   Size: {result['file_size_bytes']} bytes")

    finally:
        # Cleanup
        if Path(output_path).exists():
            Path(output_path).unlink()


def test_storyboard_export_empty():
    """Test Storyboard JSON export with empty database"""
    # Create in-memory database
    store = GraphStore("sqlite:///:memory:")

    # Create export pipeline
    engine = EnhancedQueryEngine()
    engine.store = store  # Attach store for script generation
    exporter = ExportPipeline(engine)

    # Export as Storyboard JSON
    output_path = "test_empty_storyboard.json"

    try:
        result = exporter.export_report(
            world_id="test_world",
            report_type="script",
            export_format="storyboard",
            output_path=output_path,
            title="Empty Test Storyboard"
        )

        # Verify metadata
        assert result["report_type"] == "script"
        assert result["export_format"] == "storyboard"
        assert "output_path" in result

        # Verify file was created
        assert Path(result["output_path"]).exists()

        # Read and verify JSON structure
        import json
        with open(result["output_path"]) as f:
            data = json.load(f)

        assert data["title"] == "Empty Test Storyboard"
        assert data["world_id"] == "test_world"
        assert data["temporal_mode"] == "pearl"
        assert "scenes" in data
        assert "characters" in data
        assert "metadata" in data

        print("✅ Storyboard JSON export test passed")
        print(f"   Output: {result['output_path']}")
        print(f"   Size: {result['file_size_bytes']} bytes")

    finally:
        # Cleanup
        if Path(output_path).exists():
            Path(output_path).unlink()


def test_pdf_export_empty():
    """Test PDF export with empty database"""
    # Create in-memory database
    store = GraphStore("sqlite:///:memory:")

    # Create export pipeline
    engine = EnhancedQueryEngine()
    engine.store = store  # Attach store for script generation
    exporter = ExportPipeline(engine)

    # Export as PDF
    output_path = "test_empty_script.pdf"

    try:
        result = exporter.export_report(
            world_id="test_world",
            report_type="script",
            export_format="pdf",
            output_path=output_path,
            title="Empty Test Script PDF"
        )

        # Verify metadata
        assert result["report_type"] == "script"
        assert result["export_format"] == "pdf"
        assert "output_path" in result

        # Verify file was created
        assert Path(result["output_path"]).exists()

        # Verify it's a PDF (starts with PDF magic bytes)
        with open(result["output_path"], 'rb') as f:
            header = f.read(4)
            assert header == b'%PDF', "File is not a valid PDF"

        print("✅ PDF export test passed")
        print(f"   Output: {result['output_path']}")
        print(f"   Size: {result['file_size_bytes']} bytes")

    finally:
        # Cleanup
        if Path(output_path).exists():
            Path(output_path).unlink()


def test_batch_export():
    """Test batch export of both formats"""
    # Create in-memory database
    store = GraphStore("sqlite:///:memory:")

    # Create export pipeline
    engine = EnhancedQueryEngine()
    engine.store = store
    exporter = ExportPipeline(engine)

    # Batch export both formats
    output_dir = "test_batch_output"
    Path(output_dir).mkdir(exist_ok=True)

    try:
        results = exporter.export_batch(
            world_id="test_world",
            report_types=["script"],
            export_formats=["fountain", "storyboard"],
            output_dir=output_dir,
            title="Batch Test Script"
        )

        # Verify results
        assert len(results) == 2  # One for each format

        # Check both files were created
        fountain_path = Path(output_dir) / "test_world_script.fountain"
        storyboard_path = Path(output_dir) / "test_world_script.storyboard"

        assert fountain_path.exists() or (Path(output_dir) / "test_world_script.fountain.fountain").exists()

        print("✅ Batch export test passed")
        print(f"   Exported {len(results)} files")
        for r in results:
            print(f"   - {r['export_format']}: {r['output_path']}")

    finally:
        # Cleanup
        import shutil
        if Path(output_dir).exists():
            shutil.rmtree(output_dir)


if __name__ == "__main__":
    print("=" * 60)
    print("Testing Script Export Functionality")
    print("=" * 60)
    print()

    # Run tests
    try:
        test_script_generator_basic()
        print()
        test_fountain_export_empty()
        print()
        test_storyboard_export_empty()
        print()
        test_pdf_export_empty()
        print()
        test_batch_export()
        print()
        print("=" * 60)
        print("✅ All tests passed!")
        print("=" * 60)
    except Exception as e:
        print()
        print("=" * 60)
        print(f"❌ Test failed: {e}")
        print("=" * 60)
        import traceback
        traceback.print_exc()
